output "network_id" {
  description = "The ID of the OpenStack network generated by the module"
  value       = module.networking.network_id
}

output "subnet_id" {
  description = "The ID of the OpenStack subnet generated by the module"
  value       = module.networking.subnet_id
}

output "port_id" {
  description = "The ID of the network port for the instance"
  value       = module.networking.port_id
}

output "floating_ip_address" {
  description = "The assigned public floating IP"
  value       = module.networking.floating_ip_address
}
output "security_group_id" {
  description = "The generated ID of this group to feed into your network port module"
  value       = module.security.security_group_id
}


