networks:
  app-network:
    driver: overlay

services:
  frontend:
    image: three-tier-frontend:0.0.1
    ports:
      - "8000:80"
    networks:
      - app-network
    deploy:
      replicas: 1

  backend:
    # build: ./backend
    image: three-tier-backend:0.0.1
    networks:
      - app-network
    deploy:
      replicas: 1

  db:
    image: redis:alpine
    networks:
      - app-network
    deploy:
      replicas: 1